version: "3"

services:
    api:
        build: api
        command: ["flask", "run", "--host=0.0.0.0"]
        image: marcusfooo/cz2006-backend:latest
        volumes:
            - ./api:/api
        env_file:
            - .env
        ports:
            - "5000:5000"

    client:
        build: client
        command: ["npm", "start"]
        image: marcusfooo/cz2006-frontend:latest
        volumes:
            - ./client:/frontend
            - node-modules:/frontend/node_modules/
            - client_build:/frontend/build
        env_file:
            - .env
        ports:
            - "3000:3000"
        depends_on:
            - api
        tty: true




volumes:
    node-modules:
    client_build:
