version: "3"

services:
    api:
        build: api
        command: ["flask", "run", "--host=0.0.0.0"]
        image: marcusfooo/cz2006-backend:latest
        volumes:
            - ./api:/api
        environment:
            - FLASK_ENV=development
            - FLASK_APP=./
        ports:
            - "5000:5000"

    client:
        build: client
        command: ["npm", "start"]
        image: marcusfooo/cz2006-frontend:latest
        volumes:
            - ./client:/frontend
            - node-modules:/frontend/node_modules/
            - client_build:/frontend/build
        environment:
            - NODE_ENV=development
        ports:
            - "3000:3000"
        depends_on:
            - api
        tty: true

    nginx:
        image: nginx:latest
        restart: always
        depends_on:
            - api
            - client
        volumes:
            - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
            - client_build:/var/www/frontend/build
        ports:
            - "80:80"



volumes:
    node-modules:
    client_build:
