version: "3.8"
services:
  nginx:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APPLICATION_NAME}-nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  api:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APPLICATION_NAME}-api
    build:
        context: ./api
    volumes:
      - ./api:/backend
    env_file:
      - ./api/dev.env
    ports:
      - "5000:5000"
  client:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APPLICATION_NAME}-client
    build:
      context: ./client
    volumes:
      - node-modules:/frontend/node_modules
      - ./client:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  node-modules: